{% set name = "django-admin-sortable2" %}
{% set version = "2.2.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/d4/76/8af26a825442fb33688c820cf79e4b769d8c4b976a2ddaa7434b96706e05/django_admin_sortable2-2.2.8.tar.gz"
  sha256: 59dfd7ced63e66adfb471b2a4d89ba3faae49c0148827047c8cf65759fc54c9e

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - django >=4.0
    - pip
    - python
  run:
    - django >=4.0
    - python

test:
  imports:
    - adminsortable2
    - adminsortable2.management
    - adminsortable2.management.commands

about:
  home: "https://github.com/jrief/django-admin-sortable2"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Generic drag-and-drop sorting for the List, the Stacked- and the Tabular-Inlines Views in the Django Admin"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - https://github.com/gb119
